[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # CSP consolidada para hsocial.space y funcionalidad completa
    Content-Security-Policy = "default-src 'self' https://hsocial.space https://www.hsocial.space; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://pagead2.googlesyndication.com https://*.googletagmanager.com https://*.google.com https://*.gstatic.com https://hsocial.space https://www.hsocial.space; style-src 'self' 'unsafe-inline' https://*.gstatic.com https://*.googleapis.com https://hsocial.space https://www.hsocial.space; img-src 'self' data: blob: https: http: https://hsocial.space https://www.hsocial.space; media-src 'self' data: blob: https: http: https://hsocial.space https://www.hsocial.space; connect-src 'self' https://wgbbaxvuuinubkgffpiq.supabase.co wss://wgbbaxvuuinubkgffpiq.supabase.co https://*.supabase.co wss://*.supabase.co https://api.openai.com wss://api.openai.com https://*.googleapis.com https://*.google-analytics.com https://*.googletagmanager.com https://*.googlesyndication.com https://*.google.com https://*.gstatic.com https://ep1.adtrafficquality.google https://*.cloudflare.com https://*.cloudflarestorage.com https://*.netlify.app https://r2.dev https://*.r2.dev https://hsocial.space https://www.hsocial.space; font-src 'self' https: data: https://hsocial.space https://www.hsocial.space; object-src 'none'; frame-src 'self' https: https://hsocial.space https://www.hsocial.space; frame-ancestors 'self' https://hsocial.space https://www.hsocial.space;"
    # CORS headers para tu dominio personalizado
    Access-Control-Allow-Origin = "https://hsocial.space, https://www.hsocial.space"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Aggressive caching for built assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Common static paths
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"